language: ruby
matrix:
  include:
    - env: OSX=10.11
      os: osx
      osx_image: xcode8
      rvm: system
    - os: linux
      rvm: system
      sudo: required
      dist: trusty

addons:
  apt_packages:
    - csh

before_install:
  - if [ -f ".git/shallow" ]; then
      travis_retry git fetch --unshallow;
    fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      sudo chown -R "$USER" "$(brew --repo)";
    else
      sudo mkdir -p /home/linuxbrew;
      sudo chown "$USER:" /home/linuxbrew;
      LINUXBREW=/home/linuxbrew/.linuxbrew;
      git clone https://github.com/Linuxbrew/brew.git $LINUXBREW;
      export PATH="$LINUXBREW/bin:$PATH";
    fi
  - git -C "$(brew --repo)" reset --hard origin/master;
  - git -C "$(brew --repo)" clean -qxdff;
  - brew update || brew update;
  - mkdir -p "$(brew --repo)/Library/Taps/homebrew";
  - ln -s "$TRAVIS_BUILD_DIR" "$(brew --repo)/Library/Taps/homebrew/homebrew-science";
  - cd "$(brew --repo)/Library/Taps/homebrew/homebrew-science";
  - for tap in homebrew/python homebrew/x11 homebrew/dupes homebrew/versions; do brew tap $tap; done;
  - chmod 0644 $(brew --repo)/Library/Taps/homebrew/homebrew-science/*.rb;
  - export TRAVIS_BUILD_DIR="$(brew --repo)/Library/Taps/homebrew/homebrew-science";
  - env | grep TRAVIS | tee /tmp/travis.env

install:
  - export HOMEBREW_DEVELOPER="1"
  - ulimit -n 1024

script:
  - brew test-bot --tap=homebrew/science;

notifications:
  email:
    on_success: never
    on_failure: never
